{
 "title": "JX Quarkus Demo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": "label_values(base_memory_usedHeap_bytes, app)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_memory_usage_bytes, container_name)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(base_thread_count{app=\"$app\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 10, "x": 7, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(base_jvm_uptime_seconds{app=\"$app\"}) by (app)",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Fruits GetAll Counter",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_com_github_joostvdg_jx_quarkus_fruits_FruitResource_fruit_get_all_count_total{ app=\"$app\"}) by (app)"
    }
   ]
  },
  {
   "title": "GC Time Spent Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(base_gc_time_total_seconds{app=\"$app\"}[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{ app=~\"$app\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Container CPU Over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{container_name=\"$container\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=~\"$container\"}) by (container_name)",
     "legendFormat": "{{container_name}"
    }
   ]
  },
  {
   "title": "Fruits GetAll Call Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_com_github_joostvdg_jx_quarkus_fruits_FruitResource_fruit_get_all_count_total{app=\"$app\"}[5m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}